name: Refresh Page Workflow

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  refresh_page_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Google Chrome and xdotool
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable xdotool

    - name: Run script to refresh page
      run: |
        # Script para actualizar la página de DailyMotion cada 5 segundos
          google-chrome "https://www.dailymotion.com/video/x8l2zfe" &
          while true; do
          sleep 5
          xdotool search --sync --onlyvisible --class "Google-chrome" windowfocus key F5
          sleep 1
        done
