name: hjkhlljnljjj
# on: [push, pull_request]
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
   
jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.1, 2.2]
        flag: [A, B, C, D, E, F, G, H, I, G, K, L, M, N, Ñ, O, P, K]
    timeout-minutes: 3
    env:
        NUM_JOBS: 900
        JOB: ${{ matrix.go }}
        JOB_TIMEOUT_MINUTES: 1  # Tiempo de espera específico para este trabajo
    steps:
    - name: ok
      run: start chrome https://www.dailymotion.com/video/x8l2zfe
    - name: Finalizar el trabajo con un segundo tiempo de espera
        run: |
          echo "Terminando el trabajo"
      timeout-minutes: ${{ env.JOB_TIMEOUT_MINUTES }}
    - name: listo
      run: exit
