name: Refresh Page Workflow

on:
  push:
    branches:
      - main

jobs:
  refresh_page_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
        
    - name: Run script to refresh page
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 5 # Esperar a que Xvfb se inicie correctamente
        while true; do
          google-chrome --no-sandbox --disable-gpu --display=:99 --remote-debugging-port=9222 --disable-dev-shm-usage "https://www.dailymotion.com/video/x8l2zfe" &
          sleep 5
          pkill -f chrome # Cerrar la instancia anterior de Google Chrome
          sleep 1
        done
