language: generic

services:
  - docker

before_install:
  - sudo apt-get install -y xorg

jobs:
  include:
    - name: Refresh Page Job
      script:
        - docker run -v $PWD:/workdir -w /workdir ubuntu:latest /bin/bash -c "apt update && apt install -y google-chrome-stable xdotool && google-chrome 'https://www.dailymotion.com' & while true; do sleep 5; xdotool search --sync --onlyvisible --class 'Google-chrome' windowfocus key F5; sleep 1; done"
