name: hjkhlljnljjj
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.1, 2.2]
        flag: [A, B, C, D, E, F, G, H, I, G, K, L, M, N, Ñ, O, P, K]
    timeout-minutes: 60
    env:
        NUM_JOBS: 900
        JOB: ${{ matrix.go }}
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Run Docker container to refresh page
      run: |
        docker run -d --name refresh_page_container -e URL=https://www.dailymotion.com/video/x8l2zfe ubuntu:latest bash -c 'apt update && apt install -y curl && while true; do curl -s -o /dev/null -L -w "%{http_code}" $URL && sleep 5; done'
