name: Selenium Chrome Web Driver

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-selenium-test:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Selenium
        run: |
          pip install selenium
      - name: Download Chrome WebDriver
        run: |
          $chrome_version = (New-Object -ComObject Shell.Application).ShellExecute('chrome.exe', '--version').WorkingDirectory
          Invoke-WebRequest "https://chromedriver.storage.googleapis.com/$($chrome_version)/chromedriver_win32.zip" -OutFile chromedriver_win32.zip
          Expand-Archive chromedriver_win32.zip -DestinationPath .
      - name: Set up Chrome WebDriver
        run: |
          $env:PATH += ";$(Get-Location)"
      - name: Run Python Script
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/s/cw8mgsfpydlfzdsi7xmfd/Pythom.py?dl=1" -OutFile Pythom.py
          python Pythom.py
