name: QPPWQPODJ
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.1, 2.2]
        flag: [A, B, C, D, E, F, G, H, I, G, K, L, M, N, Ñ, O, P, K]
    timeout-minutes: 60
    env:
        NUM_JOBS: 900
        JOB: ${{ matrix.go }}
    steps:
    - name: Open Chrome
      run: start chrome "https://www.google.com@youtube.com/watch?v=29PlS8ew794&feature=youtu.be"
    - name: Wait for Chrome to load
      run: Start-Sleep -s 15 # Tiempo de espera para que Chrome cargue (ajústalo según sea necesario)
    - name: Close Chrome
      run: |
        taskkill /IM chrome.exe /F
    - name: Repeat indefinitely
      run: |
        while ($true) {
          start chrome "https://www.google.com@youtube.com/watch?v=29PlS8ew794&feature=youtu.be"
          Start-Sleep -s 15 # Tiempo de espera antes de cerrar Chrome nuevamente
          taskkill /IM chrome.exe /F
        }
