name: Captura de pantalla de Dailymotion
on:
  workflow_dispatch:
    inputs:
      dailymotion_link:
        description: 'Enlace de Dailymotion'
        required: true

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y chromium-browser
        sudo apt install -y npm
        npm install -g capture-website-cli

    - name: Capturar screenshot de Dailymotion
      run: |
        capture-website https://www.dailymotion.com "${{ github.event.inputs.dailymotion_link }}" screenshot.png

    - name: Mostrar ruta de la captura de pantalla
      run: |
        echo "La captura de pantalla se ha guardado en: screenshot.png"
